### ISSUE TITLE
Only one production allowed

### ISSUE THREAD

**Issue by SrTobi** [tyml/extensive-grammar-language#1]
The EGL for EGL only allows one production.
A rule like

```
EGL ::= Production+
```

is missing

**Comment by hediet** [comment]
Actually, the production rules at the end don't describe the full grammar as a grammar consists of an alphabet, a start symbol and all production rules. However, when specifying a new language, all these production rules are embedded in continous text, so I don't think it is sensefull to introduce a formal mechanism to describe the whole grammar rathar than just all productions. This also answers the "Grammar may not start with WS?" question. What do you think?
