### ISSUE TITLE
Ambigous in Concat with Opt, Star and PosStar

### ISSUE THREAD

**Issue by SrTobi** [tyml/extensive-grammar-language#2]
Consider

```
S ::= ab?
```

Could be
1. `S -> Opt(Symbol("ab"))`
2. or `S -> Concat(Symbol("a"), Opt("b"))`

**Comment by hediet** [comment]
Thanks!
Fixed in 594a73b2e45891effa8147e0f12760f74ebe0922 by adding the conditional disjunction.
Because `ab` matches the `Symbol` production already, it won't match `Concat \ Symbol`.
