### ISSUE TITLE
Strings and character classes not defined not defined

### ISSUE THREAD

**Issue by SrTobi** [tyml/extensive-grammar-language#4]
Strings like

```
S ::= "test"
```

or character classes like

```
S ::= [abc]
```

are net mentioned in the EGL of EGL.

**Comment by hediet** [comment]
This is because I excluded the unicode extensions for this example to keep it short (and because I was too lazy to do that :smile: ). I will add that!

**Comment by hediet** [comment]
Btw. character classes are something different, I think you mean character ranges.
However, I added the productions for these extensions.
